### PR TITLE
Junction fixes

### PR DESCRIPTION
**Pull request by alevar**
Junction coordinates had a typo: fstart/fend instead of start/end

### CODE REVIEW

**Comment by gpertea** [comment]
That junction BED format is a rather unusual way to represent the "junction" data, the actual junction coordinates are never really in there.  The purpose of writing that file from TieCov (for me, sorry I took over your utility name and some code there!) was for IGV loading and visualization, hence the unnecessarily convoluted representation of the junction coverage data, I agree.. It took me a while to figure out the format needed for that (even though I worked on TopHat never had to deal with that particular feature), I gathered the documentation I found about it in this document:
https://github.com/gpertea/tiebrush/blob/master/TODO.md

As you see there, each junction BED line is actually represented as a 2-block (exon) alignment  so the junction is there inbetween those blocks. Obviously one can easily recover the actual junction coordinates from that exon-based representation with some simple arithmetic.

If you needed just the junction (intron) coordinates and their coverage plainly written in a file perhaps we should add another TieCov option to write the much simpler 4-column format (so not BED as that would not be suitable as the 4th column should simply have the junction coverage count).

**Comment by alevar** [comment]
Ah, i was not aware of that format - that's my bad. And thank you for the explanation! I think simple bed might be useful for junctions as well (less storage space and easier to parse for uses other than IGV). For example "K03455	4000	6000	JUNC00000001	1000	-" seems to work with IGV as intended and misses only the flanking lengths information.

On a side note, I noticed the current implementation uses uint16_t to store coverage in bcov. In the most recent commit I changed the definition to uint32_t since a lot of junctions in GTEx have coverage well over 65K.

I was also trying to understand "if (vs) dupcount=1;" in the CJunc constructor. Doesn't this always remove any information from the YC tag?

**Comment by gpertea** [comment]
Thank you for the bcov fix, I didn't realize the coverage is getting so high. 
Thank you for catching that oops in the CJunc constructor, it does seems like an ugly bug (!), I have no idea why I put that in there -- probably a leftover from the first version of that constructor where the actual dupcount value was not passed to the constructor.. Eek.

I'd have to check how a simpler BED file to represent junctions loads in IGV, I don't care about the flanking information -- and I'd be rather annoyed to find out that the IGV documentation did not make it clear that I can also use that simpler BED format to load a junction coverage track, after I specifically followed their clues about how to create that 2-block junctions bed file..

**Comment by alevar** [comment]
Yeah, IGV documentation does not seem most easy to follow. My understanding base on http://software.broadinstitute.org/software/igv/splice_junctions they state was that standard BED is accepted which I tested in my local IGV installation with the example format above. It seems like the first 3 columns are required as well as the "track name=junctions" header.

it seems additional columns are parsed as per BED "optional fields" order with score indicating coverage of the junction. Just using the first 6 fields seems to have provided me with all information I needed to be displayed in IGV.

**Pull request merged**
